webapp/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_user import UserMixin, current_user
from sqlalchemy_utils.types.choice import ChoiceType

from webapp.external_services.unbabel_api import request_words

db = SQLAlchemy()


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    active = db.Column('is_active', db.Boolean(), nullable=False, server_default='1')

    username = db.Column(db.String(255), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False, server_default='')

    # User information
    first_name = db.Column(db.String(100), nullable=False, server_default='')
    last_name = db.Column(db.String(100), nullable=False, server_default='')
    translations = db.relationship('Translation', backref='user', lazy='dynamic')

    # Define the relationship to Role via UserRoles
    roles = db.relationship('Role', secondary='user_roles')


# Define the Role data-model
class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), unique=True)


# Define the UserRoles association table
class UserRoles(db.Model):
    __tablename__ = 'user_roles'
    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='CASCADE'))
    role_id = db.Column(db.Integer(), db.ForeignKey('roles.id', ondelete='CASCADE'))


class Translation(db.Model):
    STATUS = [
        ('new', 'new'),
        ('translating', 'translating'),
        ('completed', 'completed'),
        ('failed', 'failed'),
        ('canceled', 'canceled'),
        ('accepted', 'accepted'),
        ('rejected', 'rejected')
    ]
    __tablename__ = 'translations'
    uid = db.Column(db.String, primary_key=True, nullable=False)
    original_text = db.Column(db.Text, nullable=False)
    translated_text = db.Column(db.Text, nullable=True)
    original_language = db.Column(db.String, nullable=False)
    translated_language = db.Column(db.String, nullable=False)
    size = db.Column(db.Integer, nullable=False)
    status = db.Column(ChoiceType(STATUS))
    owner_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'))
    created_on = db.Column(db.DateTime, server_default=db.func.now())
    updated_on = db.Column(db.DateTime, server_default=db.func.now(),
                           server_onupdate=db.func.now())


def save_translation(new_translation):
    translation = Translation(uid=new_translation.uid, original_text=new_translation.text,
                              original_language=new_translation.source_language,
                              translated_language=new_translation.target_language,
                              status=new_translation.status,
                              size=0,
                              owner_id=current_user.id
                              )

    db.session.add(translation)
    db.session.commit()


def update_translation_model(updated_translation):
    translation = Translation.query.filter_by(uid=updated_translation.get('uid')).first()
    translation.status = updated_translation.get('status')
    translation.translated_text = updated_translation.get('translated_text')
    translation.size = request_words(updated_translation.get('translated_text'))

    db.session.commit()


def patch_status_translations_model(list_translations):
    uid_list = [t.uid for t in list_translations]
    transl_to_update = Translation.query.filter(Translation.uid.in_(uid_list))
    for transl in transl_to_update:
        transl.status = [x.status for x in list_translations if x.uid == transl.uid]
        db.session.commit()

webapp/views/admin_views.py
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_user import current_user


class DashboardModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.has_roles('Admin')

    can_delete = False  # disable model deletion
    can_create = False
    can_edit = False
    can_export = True
    page_size = 50  # the number of entries to display on the list view


class HomeView(AdminIndexView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.has_roles('Admin')

webapp/views/translation_views.py
from flask import Blueprint, render_template, request, redirect
from flask_user import login_required, current_user

from webapp.external_services.unbabel_api import request_babel_translation
from webapp.models import Translation, update_translation_model, save_translation

translation_bp = Blueprint('translation_bp', __name__, template_folder='templates')
translation_bp.config = {}


@translation_bp.record_once
def record_params(state):
    """Store app.config in blueprint when blueprint is registered on app."""
    app = state.app
    translation_bp.config = app.config


@translation_bp.route('/translation', methods=['GET', 'POST'])
@login_required
def translate():
    if request.method == 'POST':
        new_translation = request_babel_translation(request.form.get('text'), 'en', 'es',
                                                    translation_bp.config['CALLBACK_URL'])
        save_translation(new_translation)
        return redirect('/translations_list')
    else:
        return render_template('translation/translation.html')


@translation_bp.route('/translations_list', methods=['GET'])
@login_required
def translation_list():
    transl_list = Translation.query.filter_by(owner_id=current_user.id).order_by(
        Translation.size.desc()).all()
    return render_template('translation/translations_list.html', translation_list=transl_list)


@translation_bp.route('/update_translation', methods=['POST'])
def update_translation():
    update_translation_model(request.form)
    return request.form.get('status')


@translation_bp.route('/get_translation/<string:translation_uid>', methods=['GET'])
def get_translation(translation_uid):
    detail = Translation.query.filter_by(uid=translation_uid).first()
    return render_template('translation/translation_detail.html', translation=detail)

webapp/views/user_views.py
from flask import Blueprint, render_template


users_bp = Blueprint('users_bp', __name__, template_folder='templates')


@users_bp.route('/')
def home():
    return render_template('home.html')

webapp/templates/base.html
{% extends "bootstrap/base.html" %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
    <title> {% block title %}Basic Translation APP {% endblock %}</title>
</head>
<body>

<div>Navbar</div>
{% block content %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('users_bp.home') }}">Basic Translation
                    APP</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/translation">Translation</a></li>
                    <li><a href="/translations_list">Translation List</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {% if call_or_get(current_user.is_authenticated and current_user.has_roles('Admin')) %}
                            <a href="{{ url_for('admin.index') }}">{% trans %}
                                Admin{% endtrans %}</a>
                        {% endif %}
                    <li>{% if call_or_get(current_user.is_authenticated) %}
                        <a href="{{ url_for('user.logout') }}">{% trans %}Sign
                            out{% endtrans %}</a>
                    {% else %}
                        <a href="{{ url_for('user.login') }}">{% trans %}Sign
                            in{% endtrans %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
{% endblock %}
</body>
</html>

webapp/templates/flask_user/_authorized_base.html
{% extends 'flask_user/_common_base.html' %}

webapp/templates/flask_user/_common_base.html
{% extends "flask_user_layout.html" %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-sm-7 col-md-6 col-lg-5 col-centered">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/flask_user/_macros.html
{% macro render_field(field, label=None, label_visible=true, right_url=None, right_label=None) -%}
    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {% if field.type != 'HiddenField' and label_visible %}
            {% if not label %}{% set label=field.label.text %}{% endif %}
            <label for="{{ field.id }}" class="control-label">{{ label|safe }}</label>
        {% endif %}
        {{ field(class_='form-control', **kwargs) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>
{%- endmacro %}
 
{% macro render_checkbox_field(field, label=None) -%}
    {% if not label %}{% set label=field.label.text %}{% endif %}
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ label }}
        </label>
    </div>
{%- endmacro %}
 
{% macro render_radio_field(field) -%}
    {% for value, label, checked in field.iter_choices() %}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}"{% if checked %} checked{% endif %}>
                {{ label }}
            </label>
        </div>
    {% endfor %}
{%- endmacro %}

{% macro render_submit_field(field, label=None, tabindex=None) -%}
    {% if not label %}{% set label=field.label.text %}{% endif %}
    {#<button type="submit" class="form-control btn btn-default btn-primary">{{label}}</button>#}
    <input type="submit" class="btn btn-default btn-primary" value="{{label}}"
           {% if tabindex %}tabindex="{{ tabindex }}"{% endif %}
           >
{%- endmacro %}

webapp/templates/flask_user/_public_base.html
{% extends 'flask_user/_common_base.html' %}

webapp/templates/flask_user/login.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
 <div class="col-md-8 col-md-offset-2">
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
<h1>{%trans%}Sign in{%endtrans%}</h1>

<form action="" method="POST" class="form" role="form">
    {{ form.hidden_tag() }}

    {# Username or Email field #}
    {% set field = form.username if user_manager.USER_ENABLE_USERNAME else form.email %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        {# Label on left, "New here? Register." on right #}
        <div class="row">
            <div class="col-xs-6">
                <label for="{{ field.id }}" class="control-label">{{ field.label.text }}</label>
            </div>
            <div class="col-xs-6 text-right">
                {% if user_manager.USER_ENABLE_REGISTER and not user_manager.USER_REQUIRE_INVITATION %}
                    <a href="{{ url_for('user.register') }}" tabindex='190'>
                        {%trans%}New here? Register.{%endtrans%}</a>
                {% endif %}
            </div>
        </div>
        {{ field(class_='form-control', tabindex=110) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>

    {# Password field #}
    {% set field = form.password %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        {# Label on left, "Forgot your Password?" on right #}
        <div class="row">
            <div class="col-xs-6">
                <label for="{{ field.id }}" class="control-label">{{ field.label.text }}</label>
            </div>
            <div class="col-xs-6 text-right">
                {% if user_manager.USER_ENABLE_FORGOT_PASSWORD %}
                    <a href="{{ url_for('user.forgot_password') }}" tabindex='195'>
                        {%trans%}Forgot your Password?{%endtrans%}</a>
                {% endif %}
            </div>
        </div>
        {{ field(class_='form-control', tabindex=120) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>

    {# Remember me #}
    {% if user_manager.USER_ENABLE_REMEMBER_ME %}
    {{ render_checkbox_field(login_form.remember_me, tabindex=130) }}
    {% endif %}

    {# Submit button #}
    {{ render_submit_field(form.submit, tabindex=180) }}
</form>

 </div>
{% endblock %}

webapp/templates/flask_user/login_auth0.html
{% extends "flask_user_layout.html" %}

{% block extra_css %}
<style>
    /* Create full height content */
    html, body, #centered-block {
        min-height: 100%;
        height: 100%;
    }
    #main-div {
        min-height: 75%;
        height: 75%;
    }
    /* Center "Sign in" button */
    #centered-block {
        display: flex;
        align-items: center;
        justify-content: center;
    }
</style>
{% endblock %}

{% block content %}
<div id="centered-block">
    <a class="btn btn-primary"
        href="{{ url_for('user.login') }}">Sign in</a>
</div>
{% endblock %}

{% block extra_js %}
{# Load Auth0 javascript library #}
<script src="https://cdn.auth0.com/js/lock/10.18.0/lock.min.js"></script>

<script>
{# Create and show Auth0 login widget called Auth0Lock when the document has finished loading #}
$(document).ready(function() {

    {# Create the Auth0 Lock login widget #}
    {# AUTH0_CLIENT_ID and AUTH0_DOMAIN are defined by the Auth0 website #}
    var auth0_lock = new Auth0Lock('{{ config.get('AUTH0_CLIENT_ID') }}', '{{ config.get('AUTH0_DOMAIN') }}', {
        auth: {
            {# auth0_callback_url is something like "https://app.registersimply.com/callback" #}
            {# and must be defined in the Auth0 website for it to work #}
            redirectUrl: 'http://localhost:5000/callbacks/auth0',

            responseType: 'code',       // Return as Auth0 Code

            params: {
                scope: 'openid email',   // Return user ID and email in the user_info
                state: '{{ next_url }}',
            }
        },
      initialScreen: 'login'	,
      socialButtonStyle: 'small',
	  languageDictionary: {
	      emailInputPlaceholder: "you@example.com",
	      title: ""
	    },

    });

    {# Show AUTH0 Lock Widget when this page loads #}
    auth0_lock.show({
        authParams: {
            prompt: 'switch_account'    // Allow selection of multiple google accounts
        }
    });
});
</script>
{% endblock %}

webapp/templates/flask_user/login_or_register.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="col-md-8 col-md-offset-2">

        {% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}


        <div class="row">
            <div class="col-sm-6">

                <h1>{% trans %}Sign in{% endtrans %}</h1>

                {# ** Login form ** #}
                <form action="{{ url_for('user.login') }}" method="POST" class="form" role="form">
                    {{ login_form.hidden_tag() }}

                    {# Username or Email #}
                    {% set field = login_form.username if user_manager.USER_ENABLE_USERNAME else login_form.email %}
                    {{ render_field(field, tabindex=110) }}

                    {# Password #}
                    {{ render_field(login_form.password, tabindex=120) }}

                    {# Remember me #}
                    {% if user_manager.USER_ENABLE_REMEMBER_ME %}
                        {{ render_checkbox_field(login_form.remember_me, tabindex=130) }}
                    {% endif %}

                    {# Submit button #}
                    {{ render_submit_field(login_form.submit, tabindex=180) }}
                </form>
                {% if user_manager.USER_ENABLE_FORGOT_PASSWORD %}
                    <p>
                        <br/>
                        <a href="{{ url_for('user.forgot_password') }}" tabindex='190'>
                            {% trans %}Forgot your Password?{% endtrans %}</a>
                    </p>
                {% endif %}

            </div>
            <div class="col-sm-6">

                <h1>{% trans %}Register{% endtrans %}</h1>

                {# ** Register form ** #}
                <form action="{{ url_for('user.register') }}" method="POST" novalidate
                      formnovalidate class="form" role="form">
                    {{ register_form.hidden_tag() }}

                    {# Username or Email #}
                    {% set field = register_form.username if user_manager.USER_ENABLE_USERNAME else register_form.email %}
                    {{ render_field(field, tabindex=210) }}

                    {% if user_manager.USER_ENABLE_EMAIL and user_manager.USER_ENABLE_USERNAME %}
                        {{ render_field(register_form.email, tabindex=220) }}
                    {% endif %}

                    {{ render_field(register_form.password, tabindex=230) }}

                    {% if user_manager.USER_REQUIRE_RETYPE_PASSWORD %}
                        {{ render_field(register_form.retype_password, tabindex=240) }}
                    {% endif %}

                    {{ render_submit_field(register_form.submit, tabindex=280) }}
                </form>

            </div>
        </div>

    </div>
{% endblock %}

webapp/templates/flask_user/register.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="col-md-8 col-md-offset-2">
        {% from "flask_user/_macros.html" import render_field, render_submit_field %}
        <h1>{% trans %}Register{% endtrans %}</h1>

        <form action="" method="POST" novalidate formnovalidate class="form" role="form">
            {{ form.hidden_tag() }}

            {# Username or Email #}
            {% set field = form.username if user_manager.USER_ENABLE_USERNAME else form.email %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                {# Label on left, "Already registered? Sign in." on right #}
                <div class="row">
                    <div class="col-xs-6">
                        <label for="{{ field.id }}"
                               class="control-label">{{ field.label.text }}</label>
                    </div>
                    <div class="col-xs-6 text-right">
                        {% if user_manager.USER_ENABLE_REGISTER %}
                            <a href="{{ url_for('user.login') }}" tabindex='290'>
                                {% trans %}Already registered? Sign in.{% endtrans %}</a>
                        {% endif %}
                    </div>
                </div>
                {{ field(class_='form-control', tabindex=210) }}
                {% if field.errors %}
                    {% for e in field.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            {% if user_manager.USER_ENABLE_EMAIL and user_manager.USER_ENABLE_USERNAME %}
                {{ render_field(form.email, tabindex=220) }}
            {% endif %}

            {{ render_field(form.password, tabindex=230) }}

            {% if user_manager.USER_REQUIRE_RETYPE_PASSWORD %}
                {{ render_field(form.retype_password, tabindex=240) }}
            {% endif %}

            {{ render_submit_field(form.submit, tabindex=280) }}
        </form>

    </div>
{% endblock %}

webapp/templates/home.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
      {{ super() }}
    <div class="col-md-8 col-md-offset-2">
    <h1 class="leaflet-tile-pane">Basic Translation APP</h1>
        <h3>Built with Unbabel API</h3>
        <a href="https://unbabel.com"><img class="img-responsive" src="https://unbabel.com/wp-content/uploads/2018/07/unbabel-logo.png" alt="unbabel_logo"></a>

<p></p>
</div>
{% endblock %}

webapp/templates/translation/translation.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}

    <div class="col-md-8 col-md-offset-2">
        <h1>Translation</h1>

        <div class="well shadow-textarea">
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle bottom-right" type="button"
                        data-toggle="dropdown">
                    English to Spanish
                    <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li><a href="#">English to Spanish</a></li>
                </ul>
            </div>
            <form accept-charset="UTF-8" action="/translation" method="POST">
                <textarea class="form-control" id="field" name="text"
                          placeholder="Type in your text" rows="10"></textarea>
                <h6 class="pull-right" id="charNum"></h6>
                <a href="{{ url_for('translation_bp.translate') }}">
                    <button class="btn btn-primary btn-block"
                            href="{{ url_for('translation_bp.translate') }}" type="submit">Request
                        Translation
                    </button>
                </a>
            </form>
        </div>
    </div>
{% endblock %}

webapp/templates/translation/translation_detail.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="col-md-8 col-md-offset-2">
        <h1>Translation Detail</h1>
        <h3>Original Text - {{ translation.original_language }}</h3>
        <div class="well shadow-textarea">
            {{ translation.original_text }}
        </div>
        <h3>Translated Text - {{ translation.translated_language }}</h3>
        <div class="well shadow-textarea">
            {{ translation.translated_text if translation.translated_text != None}}
        </div>
    </div>

    <div class="col-md-8 col-md-offset-2">
        <h4>Additional information</h4>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col">Status</th>
                <th scope="col">Size</th>
                <th scope="col">Created On</th>
            </tr>
            </thead>
            <tbody>

            <tr class="well shadow-textarea clickable-row">
                <td>{{ translation.status.value }}</td>
                <td>{{ translation.size }}</td>
                <td>{{ translation.created_on.strftime('%Y-%m-%d') }}</td>

            </tr>

            </tbody>
        </table>
    </div>
{% endblock %}

webapp/templates/translation/translations_list.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="col-md-8 col-md-offset-2">
        <h1>Translation List</h1>
        {% if translation_list|length > 0 %}
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Original Text</th>
                    <th scope="col">Translated Text</th>
                    <th scope="col">Status</th>
                    <th scope="col">Size</th>
                    <th scope="col">Created On</th>
                </tr>
                </thead>
                <tbody>

                {% for translation in translation_list %}
                    <tr class="well shadow-textarea clickable-row">
                        <td>{{ translation.original_text[:50] }} {{ " ... " if translation.original_text|length > 50 }}</td>
                        <td>{{ translation.translated_text[:50] if translation.translated_text != None else "-" }} {{ " ... " if translation.translated_text and translation.translated_text|length > 50 }} </td>
                        <td>{{ translation.status.value }}</td>
                        <td>{{ translation.size }}</td>
                        <td>{{ translation.created_on.strftime('%Y-%m-%d') }}</td>
                        <td>
                            <a href="{{ url_for('translation_bp.get_translation', translation_uid=translation.uid) }}">more</a>
                        </td>
                    </tr>

                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="well shadow-textarea">
                <h5 class="center-block"><strong>There are no translation requests</strong></h5>
            </div>
        {% endif %}
    </div>
{% endblock %}